[general]
query = "query_node_.*"

[store]
[store.primary]
connection="postgresql://postgres:postgres@postgres:5432/graph-node"
weight = 1
pool_size = 10

[deployment]
[[deployment.rule]]
indexers = [ "index_node_acala_0" ]

[chains]
ingestor = "index_0"

[chains.acala]
shard = "primary"
provider = [
  { label = "acala-rpc-0", url = "http://host.docker.internal:8545", features = ["archive", "traces", "no_eip1898"] }
]
